2019-11-24 16:41:47,785 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTc0NjEwNjk3LjU4MzAzNX0.g3z4BSo74zcIuuLWgvBimHcI3e18Rf-jqlFl-XZxA04 [GET] [in /Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amirsciammas/PycharmProjects/microblog/app/routes.py", line 167, in reset_password
    user = current_user.verify_reset_password_token(token)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'verify_reset_password_token'
2019-11-24 16:43:42,166 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTc0NjEwNjk3LjU4MzAzNX0.g3z4BSo74zcIuuLWgvBimHcI3e18Rf-jqlFl-XZxA04 [GET] [in /Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amirsciammas/PycharmProjects/microblog/app/routes.py", line 167, in reset_password
    user = current_user.verify_reset_password_token(token)
  File "/Users/amirsciammas/PycharmProjects/microblog/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'verify_reset_password_token'
2019-11-24 16:45:19,428 INFO: Microblog startup [in /Users/amirsciammas/PycharmProjects/microblog/app/__init__.py:48]
2019-11-24 17:04:07,573 INFO: Microblog startup [in /Users/amirsciammas/PycharmProjects/microblog/app/__init__.py:50]
2019-11-24 17:04:28,128 INFO: Microblog startup [in /Users/amirsciammas/PycharmProjects/microblog/app/__init__.py:50]
2019-11-24 17:16:49,808 INFO: Microblog startup [in /Users/amirsciammas/PycharmProjects/microblog/app/__init__.py:52]
